[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
    "npm ci --ignore-scripts",
    "cd server && npm ci --ignore-scripts",
    "cd client && npm ci --ignore-scripts"
]

[phases.build]
cmds = [
    "npm run build",
    "cd server && ./node_modules/.bin/prisma generate"
]

[start]
cmd = "cd server && ./node_modules/.bin/prisma migrate deploy && node src/index.js"
